# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release new version

on:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REPO_SECRET_KEY }}
    - run: git config --local user.email "jaroslaw.palka@symentis.pl"
    - run: git config --local user.name "Jarosław Pałka"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Prepare for release
      run: ./mvnw -B -DignoreSnapshots=true release:prepare release:perform
